version: '3.7'

services:

  traefik:
    image: traefik:v2.2
    command:
      - --entrypoints.web.address=:80
      - --providers.docker
      - --api.insecure
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  gru:
    build:
      dockerfile: Dockerfile.dev
      context: ./gru
    volumes:
      - /app/node_modules
      - /app/data
      - /app/node
      - /app/tool_bin
      - /app/static
      - ./gru:/app
    labels:
      - traefik.http.routers.gru.rule=Host(`gru.iobio`)

  gene:
    build:
      dockerfile: Dockerfile.dev
      context: ./gene
    volumes:
      - /app/node_modules
      - ./gene:/app
    labels:
      - traefik.http.routers.gene.rule=Host(`gene.iobio`)
