# Compose file for local development (not yet tested after updates to docker swarm deployment on 9/7/21)
#
# - proxy with dynamic routing & dashboard
# - gene.iobio client app
# - gru.iobio api

version: "3.8"

services:

  traefik:
    image: traefik:v2.5.2
    command:
      # - --api.debug=true
      # - --log.level=ERROR
      - --entrypoints.web.address=:80
      - --providers.docker
      - --api.insecure
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  gru:
    build:
      dockerfile: ./docker/prod/Dockerfile
      context: ./gru
    volumes:
      - /iobio-gru-backend/node_modules
      - /iobio-gru-backend/tool_bin
      - /iobio-gru-backend/static
      - ./gru:/iobio-gru-backend
      - ./sqlite/data:/iobio-gru-backend/data:ro
    labels:
      - "traefik.http.routers.gru.rule=Host(`gru.localhost`)"
      - "traefik.http.services.gru.loadbalancer.server.port=9001"

  gene:
    build:
      dockerfile: Dockerfile.dev
      context: ./gene
    volumes:
      - /app/node_modules
      - ./gene:/app
    labels:
      - "traefik.http.routers.gene.rule=Host(`gene.localhost`)"
