# Compose file for local development
#
# - proxy with dynamic routing & dashboard
# - gene.iobio client app
# - gru.iobio api

version: "3.7"

services:

  traefik:
    image: traefik:v2.1
    command:
      # - --api.debug=true
      # - --log.level=ERROR
      - --entrypoints.web.address=:80
      - --providers.docker
      - --api.insecure
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  gru:
    build:
      dockerfile: Dockerfile
      context: ./gru
    privileged: true
    volumes:
      - /app/node_modules
      - /app/tool_bin
      - /app/static
      - ./gru:/app
      - ./sqlite/data:/app/data
    labels:
      - "traefik.http.routers.gru.rule=Host(`gru.localhost`)"
      - "traefik.http.services.gru.loadbalancer.server.port=9001"

  gene:
    build:
      dockerfile: Dockerfile.dev
      context: ./gene
    volumes:
      - /app/node_modules
      - ./gene:/app
    labels:
      - "traefik.http.routers.gene.rule=Host(`gene.localhost`)"
