version: '3.7'

services:

  gru:
    build:
      dockerfile: Dockerfile.dev
      context: ./gru
    volumes:
      - /app/node_modules
      - /app/data
      - /app/node
      - /app/tool_bin
      - /app/static
      - ./gru:/app
    ports:
      - "9001:9001"

  gene:
    build:
      dockerfile: Dockerfile.dev
      context: ./gene
    volumes:
      - /app/node_modules
      - ./gene:/app
    ports:
      - "3000:3000"
