# Stack to deploy the iobio apps behind traefik on proxy network.
#
# - gene.iobio client app
# - gru.iobio api
#
# Prerequisites - Must complete before launching stack
#
# 1. Launch the traefik stack
# 2. Replace all instances of example frameshift domains (iobio.frameshift.io)

version: "3.9"

services:

  gene:
    image: ${GENE_REPOSITORY}
    networks:
      - proxy
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.gene.rule=Host(`iobio.frameshift.io`)"
        - "traefik.http.routers.gene.entrypoints=websecure"
        - "traefik.http.routers.gene.tls=true"
        - "traefik.http.routers.gene.tls.certresolver=leresolver"
        - "traefik.http.services.gene.loadbalancer.server.port=80"

  gru:
    image: ${GRU_REPOSITORY}
    networks:
      - proxy
    volumes:
        - ../sqlite/gru_data:/gru_data
    deploy:
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.gru.rule=Host(`iobio.frameshift.io`) && PathPrefix(`/api/`)"
        - "traefik.http.routers.gru.entrypoints=websecure"
        - "traefik.http.routers.gru.tls=true"
        - "traefik.http.routers.gru.tls.certresolver=leresolver"
        - "traefik.http.routers.gru.middlewares=strip-api-prefix,gru-compress"
        - "traefik.http.middlewares.strip-api-prefix.stripprefix.prefixes=/api"
        - "traefik.http.middlewares.strip-api-prefix.stripprefix.forceslash=false"
        - "traefik.http.middlewares.gru-compress.compress=true"
        - "traefik.http.services.gru.loadbalancer.server.port=9001"

networks:
  proxy:
    external: true
