version: '3.7'

services:

  gene:
    image: frameshiftgenomics/iobio_gene:latest
    networks:
      - frontend
      - proxy
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.gene.rule=Host(`iobio.frameshift.io`)"
        - "traefik.http.services.gene.loadbalancer.server.port=80"
        - "traefik.http.routers.gene.entrypoints=websecure"
        - "traefik.http.routers.gene.tls=true"
        - "traefik.http.routers.gene.tls.certresolver=leresolver"

networks:
  frontend:
  proxy:
    external: true
